In [1]:
import numpy as np
import pandas as pd

In [2]:
class DataManager:
    def __init__(self):
        self.feature = None
        self.rdf = None # raw df
        self.data = None # dictionary of processed dfs data
        self.X = None
        self.y = None
        self.tdata = None
        
    def read_training_data(self, file_name):
        df = pd.read_csv(file_name, encoding='big5', na_values=['NR'])
        df = df.fillna(0.0)
        df = df.rename(columns={
            df.columns[0]: 'date',
            df.columns[1]: 'location',
            df.columns[2]: 'feature'
        })
        df.date = pd.to_datetime(df.date)
        df = df.drop(columns=['location'])
        self.feature = sorted(df.feature.unique())
        self.rdf = df
        self.rdf_to_data()
        return 
    
    def rdf_to_data(self):
        rdf = self.rdf
        data = {month: {feature: df.drop(columns=['date', 'feature']).values.flatten() for feature, df in mdf.groupby(mdf.feature)} for month, mdf in rdf.groupby(rdf.date.dt.month)}
        self.data = data
        return 
    
    def select_feature_to_mdfs(self, feature_list=None):
        if feature_list is None:
            feature_list = self.feature
#         mdfs = {month: pd.DataFrame(columns=feature_list) for month in range(1, 13)}
        mdfs = {month: pd.DataFrame(columns=sorted(feature_list)) for month in range(1, 13)}

        for month, fdata in self.data.items():
            for feature in feature_list:
                mdfs[month][feature] = fdata[feature]
            
        return mdfs
    
    
    def chunk_examples(self, mdfs, chunk_size):
        X = []
        y = []
        for month, mdf in mdfs.items():
            nrows, ncols = mdf.shape

            for i in range(nrows-chunk_size):
#                 X.append(mdf.iloc[i:i+chunk_size].T.values.flatten())
                X.append(mdf.iloc[i:i+chunk_size].values.flatten())
                y.append(mdf.loc[i+chunk_size, 'PM2.5'])
                
        X = np.array(X)
        y = np.array(y).reshape((-1, 1))
        return X, y
    
    def read_testing_data(self, file_name):
        df = pd.read_csv(file_name, header=None, na_values=['NR'])
        df = df.rename(columns={0: 'id', 1: 'feature'})
        df = df.fillna(0.0)
        self.tdata = df
        return
    
    def select_testing_feature(self, feature_list=None):
        if feature_list is None:
            feature_list = self.feature
            
        iddfs = {i: df for i, df in self.tdata.groupby(self.tdata.id)}
        
        for i, df in iddfs.items():
            columns = df.feature
            df = df.drop(columns=['id', 'feature']).T
            df.columns = columns
            df = df[sorted(feature_list)]
#             df = df[feature_list]
            iddfs[i] = df
        return iddfs
            

In [3]:
def normalize_data(X):
    mu = np.mean(X, axis=0)
    sigma = np.std(X, axis=0)
    X_n = (X - mu) / sigma
    return X_n, mu, sigma

In [4]:
def norm_eq(X, y):
    theta = np.dot(np.dot(np.linalg.pinv(np.dot(X.T, X)), X.T), y)
    return theta

In [5]:
def predict(theta, instance):
    h_theta = np.dot(instance, theta)
    return h_theta

In [6]:
dm = DataManager()

In [7]:
dm.read_training_data('./train.csv')

In [8]:
mdfs = dm.select_feature_to_mdfs(['PM2.5', 'PM10'])

In [9]:
X, y = dm.chunk_examples(mdfs, chunk_size=9)

In [10]:
X_n, mu, sigma = normalize_data(X)

In [11]:
norm_theta = norm_eq(np.insert(X_n, obj=0, values=1, axis=1), y)

In [12]:
dm.read_testing_data('./test.csv')

In [13]:
tX = dm.select_testing_feature(['PM2.5', 'PM10'])

In [14]:
results = []
for i, tdf in tX.items():
    instance_n = (tdf.values.flatten() - mu) / sigma
#     instance_n = (tdf.T.values.flatten() - mu) / sigma

#     print(tdf.T.values.flatten())
    results.append((i, predict(norm_theta, np.insert(instance_n.reshape((1, -1)), obj=0, values=1, axis=1))[0, 0]))
results = np.array(results)

In [16]:
pd.DataFrame(results, columns=['id', 'value'])

id               value
0      id_0  35.397056919205596
1      id_1  13.717200901715609
2     id_10  27.518308420229843
3    id_100  23.549114008512184
4    id_101  51.143232881431636
5    id_102  25.490830295143706
6    id_103   36.42587945163841
7    id_104   29.97024579255344
8    id_105  24.710147116082457
9    id_106    18.1164509759114
10   id_107  36.766326627978856
11   id_108  10.800693552933648
12   id_109   70.02732807300782
13    id_11   36.02258760870484
14   id_110  28.846764505791604
15   id_111   71.93353679537647
16   id_112  23.594700207448124
17   id_113  27.666509431872072
18   id_114    30.4340044448129
19   id_115   38.31779574594272
20   id_116  37.678344185430895
21   id_117   21.67487695049281
22   id_118   30.31502695201275
23   id_119  49.418994426947684
24    id_12  39.901307876249184
25   id_120  25.635959669502853
26   id_121  33.140144347616385
27   id_122   71.85613508816442
28   id_123   8.463505189493013
29   id_124    37.3841441301702
..      ...                 ...
230   id_72  32.832302711663615
231   id_73  14.705888430693436
232   id_74  53.057757877956824
233   id_75   62.00463169162238
234   id_76  10.130173181065722
235   id_77    36.7038315178322
236   id_78   77.12807744087324
237   id_79   46.16087217448296
238    id_8   32.21873555995903
239   id_80   53.24158195522834
240   id_81   24.42571371561299
241   id_82  14.606590235720532
242   id_83   42.01012886313097
243   id_84  16.252215891362567
244   id_85  13.311198140273937
245   id_86  30.044021074136825
246   id_87   89.25282207116284
247   id_88   29.52094035767976
248   id_89  43.977041293786236
249    id_9   19.61686157254909
250   id_90  16.603074397769305
251   id_91  63.947562157775394
252   id_92  58.766381708102855
253   id_93   9.901464359698537
254   id_94  24.719216496177438
255   id_95  26.796021888247864
256   id_96   25.19452890776488
257   id_97   4.784675380421394
258   id_98   16.47805266366741
259   id_99   33.46434493308956

[260 rows x 2 columns]

In [16]:
mdfs[1]

PM10  PM2.5
0     91.0   58.0
1    104.0   59.0
2     87.0   57.0
3     91.0   59.0
4     83.0   64.0
5     76.0   64.0
6     73.0   60.0
7     66.0   55.0
8     88.0   54.0
9     97.0   61.0
10   101.0   67.0
11    88.0   72.0
12    75.0   58.0
13    62.0   48.0
14    74.0   36.0
15    72.0   38.0
16    79.0   40.0
17    79.0   42.0
18    92.0   46.0
19   120.0   57.0
20   116.0   76.0
21   113.0   74.0
22    84.0   71.0
23    68.0   50.0
24    72.0   41.0
25    71.0   45.0
26    77.0   48.0
27    54.0   43.0
28    43.0   19.0
29    40.0    9.0
..     ...    ...
450  143.0   80.0
451  148.0   85.0
452  151.0   95.0
453  159.0   99.0
454  155.0  109.0
455  153.0  105.0
456  137.0  104.0
457  136.0   95.0
458  133.0   88.0
459  124.0   81.0
460  118.0   78.0
461  107.0   75.0
462  108.0   72.0
463   99.0   60.0
464  105.0   50.0
465    0.0    0.0
466    0.0   51.0
467  133.0   69.0
468  117.0   85.0
469  111.0   76.0
470  101.0   58.0
471   99.0   43.0
472   93.0   37.0
473   93.0   30.0
474   85.0   39.0
475   87.0   44.0
476   79.0   48.0
477   75.0   43.0
478   85.0   37.0
479   97.0   41.0

[480 rows x 2 columns]

In [17]:
dm.tdata

id     feature       2       3       4       5       6       7  \
0       id_0    AMB_TEMP   35.00   35.00   35.00   34.00   33.00   31.00   
1       id_0         CH4    1.60    1.70    1.70    1.60    1.60    1.60   
2       id_0          CO    0.17    0.15    0.14    0.14    0.17    0.22   
3       id_0        NMHC    0.02    0.01    0.01    0.01    0.03    0.04   
4       id_0          NO    1.60    1.70    2.00    2.10    1.90    1.80   
5       id_0         NO2    4.40    4.70    4.60    4.50    5.60    7.60   
6       id_0         NOx    6.00    6.50    6.60    6.60    7.50    9.50   
7       id_0          O3   61.00   60.00   54.00   53.00   51.00   51.00   
8       id_0        PM10   42.00   42.00   35.00   37.00   34.00   41.00   
9       id_0       PM2.5   39.00   43.00   29.00   23.00   25.00   27.00   
10      id_0    RAINFALL    0.00    0.00    0.00    0.00    0.00    0.00   
11      id_0          RH   50.00   51.00   51.00   54.00   58.00   63.00   
12      id_0         SO2    3.00    2.90    2.40    2.40    2.10    2.60   
13      id_0         THC    1.70    1.70    1.70    1.60    1.60    1.70   
14      id_0       WD_HR  269.00  261.00  269.00  267.00  270.00  278.00   
15      id_0  WIND_DIREC  260.00  265.00  276.00  267.00  278.00  278.00   
16      id_0  WIND_SPEED    3.00    3.50    3.20    3.30    3.10    2.00   
17      id_0       WS_HR    2.30    2.90    3.30    3.60    3.00    2.00   
18      id_1    AMB_TEMP   24.00   25.00   25.00   27.00   29.00   29.00   
19      id_1         CH4    1.70    1.70    1.60    1.60    1.60    1.60   
20      id_1          CO    0.13    0.12    0.16    0.22    0.24    0.19   
21      id_1        NMHC    0.03    0.02    0.04    0.05    0.11    0.11   
22      id_1          NO    0.90    1.00    1.60    2.30    4.00    3.80   
23      id_1         NO2    3.00    3.30    4.50    4.20    6.50    5.30   
24      id_1         NOx    3.90    4.30    6.10    6.50   10.00    9.00   
25      id_1          O3   23.00   21.00   18.00   19.00   20.00   22.00   
26      id_1        PM10   25.00   24.00   19.00   19.00   25.00   25.00   
27      id_1       PM2.5   18.00   13.00   22.00   18.00   14.00   10.00   
28      id_1    RAINFALL    0.00    0.00    0.00    0.00    0.00    0.00   
29      id_1          RH   67.00   65.00   65.00   64.00   58.00   58.00   
...      ...         ...     ...     ...     ...     ...     ...     ...   
4650  id_258         NOx   23.00   22.00   22.00   22.00   23.00   31.00   
4651  id_258          O3  115.00  113.00  101.00   78.00   73.00   50.00   
4652  id_258        PM10  108.00  117.00  110.00   96.00   82.00   86.00   
4653  id_258       PM2.5   69.00   71.00   61.00   55.00   47.00   43.00   
4654  id_258    RAINFALL    0.00    0.00    0.00    0.00    0.00    0.00   
4655  id_258          RH   55.00   53.00   59.00   60.00   62.00   67.00   
4656  id_258         SO2    3.60    4.10    4.40    3.00    3.80    3.50   
4657  id_258         THC    2.10    2.00    2.00    1.90    2.40    2.30   
4658  id_258       WD_HR  219.00  256.00  265.00  272.00  328.00  320.00   
4659  id_258  WIND_DIREC  238.00  279.00  266.00  287.00  318.00  322.00   
4660  id_258  WIND_SPEED    1.80    2.30    2.70    2.00    2.50    2.10   
4661  id_258       WS_HR    1.40    1.80    2.30    2.40    1.10    1.40   
4662  id_259    AMB_TEMP   21.00   21.00   21.00   21.00   21.00   20.00   
4663  id_259         CH4    1.90    1.90    2.00    2.00    2.00    2.00   
4664  id_259          CO    0.75    0.67    0.65    0.68    0.61    0.68   
4665  id_259        NMHC    0.46    0.43    0.50    0.52    0.38    0.45   
4666  id_259          NO   13.00   10.00   10.00    7.80    6.10   10.00   
4667  id_259         NO2   33.00   34.00   34.00   28.00   23.00   25.00   
4668  id_259         NOx   45.00   44.00   44.00   36.00   29.00   35.00   
4669  id_259          O3    3.60    3.60    3.50    4.50    7.90    4.10   
4670  id_259        PM10   74.00   66.00   61.00   60.00  

In [18]:
iddfs = dm.select_testing_feature(['PM2.5', 'PM10'])

In [20]:
iddfs['id_0']

feature  PM10  PM2.5
2        42.0   39.0
3        42.0   43.0
4        35.0   29.0
5        37.0   23.0
6        34.0   25.0
7        41.0   27.0
8        41.0   32.0
9        49.0   26.0
10       51.0   40.0

In [22]:
mdfs[1]

PM10  PM2.5
0     91.0   58.0
1    104.0   59.0
2     87.0   57.0
3     91.0   59.0
4     83.0   64.0
5     76.0   64.0
6     73.0   60.0
7     66.0   55.0
8     88.0   54.0
9     97.0   61.0
10   101.0   67.0
11    88.0   72.0
12    75.0   58.0
13    62.0   48.0
14    74.0   36.0
15    72.0   38.0
16    79.0   40.0
17    79.0   42.0
18    92.0   46.0
19   120.0   57.0
20   116.0   76.0
21   113.0   74.0
22    84.0   71.0
23    68.0   50.0
24    72.0   41.0
25    71.0   45.0
26    77.0   48.0
27    54.0   43.0
28    43.0   19.0
29    40.0    9.0
..     ...    ...
450  143.0   80.0
451  148.0   85.0
452  151.0   95.0
453  159.0   99.0
454  155.0  109.0
455  153.0  105.0
456  137.0  104.0
457  136.0   95.0
458  133.0   88.0
459  124.0   81.0
460  118.0   78.0
461  107.0   75.0
462  108.0   72.0
463   99.0   60.0
464  105.0   50.0
465    0.0    0.0
466    0.0   51.0
467  133.0   69.0
468  117.0   85.0
469  111.0   76.0
470  101.0   58.0
471   99.0   43.0
472   93.0   37.0
473   93.0   30.0
474   85.0   39.0
475   87.0   44.0
476   79.0   48.0
477   75.0   43.0
478   85.0   37.0
479   97.0   41.0

[480 rows x 2 columns]

In [60]:
a = np.array([[7.7]])

In [73]:
a.reshape((1,))

array([7.7])

In [75]:
a[0, 0]

7.7

In [20]:
X[147, :]

array([51., 45., 46., 38., 39., 36., 47., 55., 60., 73., 77., 62., 63.,
       70., 79., 93., 87., 96.])

In [98]:
for i in [ 77.,  74.,  69.,  65.,  66.,  75.,  79.,  91.,  92., 116., 112.,97., 107., 112., 127., 133., 122., 122.]:
    print(i in X[100, :])

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [18]:
mdfs[1]

PM2.5   PM10
0     58.0   91.0
1     59.0  104.0
2     57.0   87.0
3     59.0   91.0
4     64.0   83.0
5     64.0   76.0
6     60.0   73.0
7     55.0   66.0
8     54.0   88.0
9     61.0   97.0
10    67.0  101.0
11    72.0   88.0
12    58.0   75.0
13    48.0   62.0
14    36.0   74.0
15    38.0   72.0
16    40.0   79.0
17    42.0   79.0
18    46.0   92.0
19    57.0  120.0
20    76.0  116.0
21    74.0  113.0
22    71.0   84.0
23    50.0   68.0
24    41.0   72.0
25    45.0   71.0
26    48.0   77.0
27    43.0   54.0
28    19.0   43.0
29     9.0   40.0
..     ...    ...
450   80.0  143.0
451   85.0  148.0
452   95.0  151.0
453   99.0  159.0
454  109.0  155.0
455  105.0  153.0
456  104.0  137.0
457   95.0  136.0
458   88.0  133.0
459   81.0  124.0
460   78.0  118.0
461   75.0  107.0
462   72.0  108.0
463   60.0   99.0
464   50.0  105.0
465    0.0    0.0
466   51.0    0.0
467   69.0  133.0
468   85.0  117.0
469   76.0  111.0
470   58.0  101.0
471   43.0   99.0
472   37.0   93.0
473   30.0   93.0
474   39.0   85.0
475   44.0   87.0
476   48.0   79.0
477   43.0   75.0
478   37.0   85.0
479   41.0   97.0

[480 rows x 2 columns]

In [21]:
y

array([[61.],
       [67.],
       [72.],
       ...,
       [51.],
       [48.],
       [49.]])

In [22]:
norm_theta

array([[28.39755839],
       [-4.45330872],
       [ 2.12965279],
       [-3.32096469],
       [ 2.43711245],
       [ 9.89636874],
       [-1.27055567],
       [-0.03792362],
       [-3.23876269],
       [25.09174963],
       [ 2.41332511],
       [-0.51619257],
       [-1.28303912],
       [ 0.88566275],
       [-1.82602789],
       [-0.25125377],
       [-1.35480615],
       [ 3.62710105],
       [ 3.06946685]])

In [18]:
test_theta = np.array([[28.39755839],
       [-4.45330872],
       [ 2.12965279],
       [-3.32096469],
       [ 2.43711245],
       [ 9.89636874],
       [-1.27055567],
       [-0.03792362],
       [-3.23876269],
       [25.09174963],
       [ 2.41332511],
       [-0.51619257],
       [-1.28303912],
       [ 0.88566275],
       [-1.82602789],
       [-0.25125377],
       [-1.35480615],
       [ 3.62710105],
       [ 3.06946685]]).flatten()

In [21]:
norm_theta

array([[28.39755839],
       [ 2.41332511],
       [-4.45330872],
       [-0.51619257],
       [ 2.12965279],
       [-1.28303912],
       [-3.32096469],
       [ 0.88566275],
       [ 2.43711245],
       [-1.82602789],
       [ 9.89636874],
       [-0.25125377],
       [-1.27055567],
       [-1.35480615],
       [-0.03792362],
       [ 3.62710105],
       [-3.23876269],
       [ 3.06946685],
       [25.09174963]])

In [20]:
for i in test_theta:
    print(i in norm_theta)

False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
