In [1]:
import numpy as np
import pandas as pd

In [2]:
class DataManager:
    def __init__(self):
        self.feature = None
        self.rdf = None # raw df
        self.data = None # dictionary of processed dfs data
        self.X = None
        self.y = None
        self.tdata = None
        
    def read_training_data(self, file_name):
        df = pd.read_csv(file_name, encoding='big5', na_values=['NR'])
        df = df.fillna(0.0)
        df = df.rename(columns={
            df.columns[0]: 'date',
            df.columns[1]: 'location',
            df.columns[2]: 'feature'
        })
        df.date = pd.to_datetime(df.date)
        df = df.drop(columns=['location'])
        self.feature = sorted(df.feature.unique())
        self.rdf = df
        self.rdf_to_data()
        return 
    
    def rdf_to_data(self):
        rdf = self.rdf
        data = {month: {feature: df.drop(columns=['date', 'feature']).values.flatten() for feature, df in mdf.groupby(mdf.feature)} for month, mdf in rdf.groupby(rdf.date.dt.month)}
        self.data = data
        return 
    
    def select_feature_to_mdfs(self, feature_list=None):
        if feature_list is None:
            feature_list = self.feature
        mdfs = {month: pd.DataFrame(columns=feature_list) for month in range(1, 13)}
#         mdfs = {month: pd.DataFrame(columns=sorted(feature_list)) for month in range(1, 13)}

        for month, fdata in self.data.items():
            for feature in feature_list:
                mdfs[month][feature] = fdata[feature]
            
        return mdfs
    
    
    def chunk_examples(self, mdfs, chunk_size):
        X = []
        y = []
        for month, mdf in mdfs.items():
            nrows, ncols = mdf.shape

            for i in range(nrows-chunk_size):
                X.append(mdf.iloc[i:i+chunk_size].T.values.flatten())
                y.append(mdf.loc[i+chunk_size, 'PM2.5'])
                
        X = np.array(X)
        y = np.array(y).reshape((-1, 1))
        return X, y
    
    def read_testing_data(self, file_name):
        df = pd.read_csv(file_name, header=None, na_values=['NR'])
        df = df.rename(columns={0: 'id', 1: 'feature'})
        df = df.fillna(0.0)
        self.tdata = df
        return
    
    def select_testing_feature(self, feature_list=None):
        if feature_list is None:
            feature_list = self.feature
            
        iddfs = {i: df for i, df in self.tdata.groupby(self.tdata.id)}
        
        for i, df in iddfs.items():
            columns = df.feature
            df = df.drop(columns=['id', 'feature']).T
            df.columns = columns
#             df = df[sorted(feature_list)]
            df = df[feature_list]
            iddfs[i] = df
        return iddfs
            

In [3]:
def normalize_data(X):
    mu = np.mean(X, axis=0)
    sigma = np.std(X, axis=0)
    X_n = (X - mu) / sigma
    return X_n, mu, sigma

In [4]:
def norm_eq(X, y):
    theta = np.dot(np.dot(np.linalg.pinv(np.dot(X.T, X)), X.T), y)
    return theta

In [5]:
def predict(theta, instance):
    h_theta = np.dot(instance, theta)
    return h_theta

In [6]:
dm = DataManager()

In [7]:
dm.read_training_data('./train.csv')

In [8]:
mdfs = dm.select_feature_to_mdfs(['PM2.5', 'PM10'])

In [9]:
X, y = dm.chunk_examples(mdfs, chunk_size=9)

In [10]:
X_n, mu, sigma = normalize_data(X)

In [11]:
norm_theta = norm_eq(np.insert(X_n, obj=0, values=1, axis=1), y)

In [12]:
dm.read_testing_data('./test.csv')

In [13]:
tX = dm.select_testing_feature(['PM2.5', 'PM10'])

In [14]:
results = []
for i, tdf in tX.items():
    instance_n = (tdf.T.values.flatten() - mu) / sigma
#     print(tdf.T.values.flatten())
    results.append((i, predict(norm_theta, np.insert(instance_n.reshape((1, -1)), obj=0, values=1, axis=1))[0, 0]))
results = np.array(results)

In [18]:
pd.DataFrame(results, columns=['id', 'value']).to_csv('reproduce.csv', index=False)

In [17]:
r

id               value
0      id_0   35.39705691920548
1      id_1  13.717200901715366
2     id_10   27.51830842022988
3    id_100   23.54911400851201
4    id_101   51.14323288143199
5    id_102  25.490830295143553
6    id_103   36.42587945163847
7    id_104   29.97024579255351
8    id_105  24.710147116082467
9    id_106  18.116450975911278
10   id_107   36.76632662797907
11   id_108  10.800693552933584
12   id_109   70.02732807300808
13    id_11   36.02258760870491
14   id_110   28.84676450579142
15   id_111   71.93353679537685
16   id_112  23.594700207448128
17   id_113  27.666509431872015
18   id_114  30.434004444813223
19   id_115   38.31779574594288
20   id_116   37.67834418543134
21   id_117   21.67487695049261
22   id_118  30.315026952012868
23   id_119   49.41899442694782
24    id_12   39.90130787624939
25   id_120  25.635959669502718
26   id_121   33.14014434761642
27   id_122   71.85613508816486
28   id_123   8.463505189492883
29   id_124   37.38414413017044
..      ...                 ...
230   id_72  32.832302711663495
231   id_73  14.705888430693697
232   id_74   53.05775787795744
233   id_75   62.00463169162279
234   id_76   10.13017318106567
235   id_77   36.70383151783235
236   id_78   77.12807744087361
237   id_79  46.160872174483046
238    id_8   32.21873555995918
239   id_80   53.24158195522899
240   id_81  24.425713715613327
241   id_82  14.606590235720386
242   id_83  42.010128863130916
243   id_84  16.252215891362674
244   id_85  13.311198140273856
245   id_86  30.044021074136825
246   id_87   89.25282207116352
247   id_88  29.520940357679773
248   id_89   43.97704129378652
249    id_9  19.616861572549055
250   id_90  16.603074397769408
251   id_91   63.94756215777545
252   id_92   58.76638170810315
253   id_93   9.901464359698338
254   id_94   24.71921649617728
255   id_95  26.796021888248013
256   id_96  25.194528907764727
257   id_97   4.784675380421331
258   id_98   16.47805266366735
259   id_99   33.46434493308946

[260 rows x 2 columns]

In [88]:
dm.rdf[dm.rdf.feature=='PM2.5']

date feature      0      1     2     3     4     5     6     7  \
9    2014-01-01   PM2.5   58.0   59.0  57.0  59.0  64.0  64.0  60.0  55.0   
27   2014-01-02   PM2.5   41.0   45.0  48.0  43.0  19.0   9.0  10.0  14.0   
45   2014-01-03   PM2.5   82.0   69.0  62.0  55.0  66.0  63.0  48.0  24.0   
63   2014-01-04   PM2.5   53.0   55.0  51.0  45.0  43.0  44.0  43.0  39.0   
81   2014-01-05   PM2.5  107.0  103.0  93.0  83.0  77.0  74.0  69.0  65.0   
99   2014-01-06   PM2.5   75.0   70.0  68.0  67.0  65.0  60.0  58.0  65.0   
117  2014-01-07   PM2.5   65.0   58.0  49.0  51.0  45.0  46.0  38.0  39.0   
135  2014-01-08   PM2.5   56.0   51.0  54.0  52.0  54.0  53.0  60.0  65.0   
153  2014-01-09   PM2.5   24.0   23.0  15.0  12.0   8.0  14.0  14.0  20.0   
171  2014-01-10   PM2.5    3.0    2.0   4.0   8.0  14.0  15.0   7.0   4.0   
189  2014-01-11   PM2.5   24.0   28.0  30.0  22.0  21.0  17.0  22.0  22.0   
207  2014-01-12   PM2.5   39.0   45.0  48.0  60.0  65.0  67.0  67.0  54.0   
225  2014-01-13   PM2.5   18.0   16.0  11.0  11.0  14.0  17.0  20.0  11.0   
243  2014-01-14   PM2.5   41.0   44.0  46.0  34.0  21.0  17.0  22.0  30.0   
261  2014-01-15   PM2.5   11.0   10.0  11.0  10.0  10.0  14.0  15.0  20.0   
279  2014-01-16   PM2.5   34.0   39.0  31.0  31.0  23.0  24.0  27.0  32.0   
297  2014-01-17   PM2.5   50.0   45.0  44.0  41.0  38.0  34.0  32.0  27.0   
315  2014-01-18   PM2.5   32.0   30.0  24.0  20.0  12.0  11.0  11.0  17.0   
333  2014-01-19   PM2.5   80.0   76.0  67.0  72.0  70.0  75.0  77.0  78.0   
351  2014-01-20   PM2.5  104.0   95.0  88.0  81.0  78.0  75.0  72.0  60.0   
369  2014-02-01   PM2.5   59.0   54.0  46.0  41.0  33.0  32.0  27.0  26.0   
387  2014-02-02   PM2.5   31.0   31.0  31.0  28.0  28.0  23.0  24.0  20.0   
405  2014-02-03   PM2.5   42.0   44.0  37.0  36.0  33.0  40.0  32.0  27.0   
423  2014-02-04   PM2.5   36.0   34.0  30.0  31.0  34.0  35.0  34.0  26.0   
441  2014-02-05   PM2.5   13.0   14.0  11.0  11.0  10.0   5.0  11.0   5.0   
459  2014-02-06   PM2.5   25.0   27.0  24.0  27.0  28.0  29.0  20.0   9.0   
477  2014-02-07   PM2.5   50.0   55.0  45.0  43.0  35.0  37.0  38.0  34.0   
495  2014-02-08   PM2.5   35.0   48.0  49.0  43.0  29.0  21.0  18.0  15.0   
513  2014-02-09   PM2.5   18.0   16.0  20.0  14.0   9.0   4.0   5.0  10.0   
531  2014-02-10   PM2.5    7.0    5.0   1.0  -1.0   1.0   1.0   3.0   2.0   
...         ...     ...    ...    ...   ...   ...   ...   ...   ...   ...   
3789 2014-11-11   PM2.5   25.0   24.0  23.0  22.0  21.0  20.0  25.0  35.0   
3807 2014-11-12   PM2.5   55.0   47.0  42.0  32.0  33.0  38.0  42.0  38.0   
3825 2014-11-13   PM2.5   21.0   24.0  21.0  26.0  30.0  33.0  33.0  29.0   
3843 2014-11-14   PM2.5   19.0   16.0  17.0  19.0  16.0  18.0  19.0  31.0   
3861 2014-11-15   PM2.5   19.0   20.0  19.0  21.0  23.0  22.0  18.0  16.0   
3879 2014-11-16   PM2.5   58.0   46.0  43.0  35.0  24.0  10.0  14.0   8.0   
3897 2014-11-17   PM2.5   10.0   15.0  13.0  20.0   7.0  12.0   3.0   6.0   
3915 2014-11-18   PM2.5   14.0   18.0  17.0  12.0  13.0  12.0  18.0  21.0   
3933 2014-11-19   PM2.5   10.0   13.0   8.0  16.0  15.0  15.0  17.0  22.0   
3951 2014-11-20   PM2.5   35.0   39.0  34.0  34.0  29.0  30.0  28.0  33.0   
3969 2014-12-01   PM2.5   70.0   52.0  40.0  34.0  25.0  16.0  11.0  11.0   
3987 2014-12-02   PM2.5   26.0   21.0  26.0  22.0  24.0  28.0  32.0  31.0   
4005 2014-12-03   PM2.5   24.0   22.0  20.0  25.0  24.0  24.0  21.0  21.0   
4023 2014-12-04   PM2.5   34.0   34.0  33.0  20.0  12.0   1.0   1.0   3.0   
4041 2014-12-05   PM2.5   24.0   31.0  28.0  23.0  14.0  12.0  17.0  17.0   
4059 2014-12-06   PM2.5   49.0   52.0  53.0  48.0  40.0  35.0  37.0  36.0   
4077 2014-12-07   PM2.5    0.0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   
4095 2014-12-08   PM2.5   45.0   43.0  40.0  49.0  44.0  38.0  32.0  33.0   
4113 2014-12-09   PM2.5   31.0   26.0  27.0  24.0  14.0  18.0  18.0  25.0   
4131 2014-12-10   PM2.5   52.0   55.0  46.0  46.0  48.0  56.0  55.0  54.0   
4149 20

In [82]:
X.shape

(5652, 18)

In [48]:
b.columns = c

In [49]:
b

feature  AMB_TEMP  CH4    CO  NMHC   NO   NO2   NOx    O3  PM10  PM2.5  \
2            35.0  1.6  0.17  0.02  1.6   4.4   6.0  61.0  42.0   39.0   
3            35.0  1.7  0.15  0.01  1.7   4.7   6.5  60.0  42.0   43.0   
4            35.0  1.7  0.14  0.01  2.0   4.6   6.6  54.0  35.0   29.0   
5            34.0  1.6  0.14  0.01  2.1   4.5   6.6  53.0  37.0   23.0   
6            33.0  1.6  0.17  0.03  1.9   5.6   7.5  51.0  34.0   25.0   
7            31.0  1.6  0.22  0.04  1.8   7.6   9.5  51.0  41.0   27.0   
8            30.0  1.7  0.30  0.08  1.8  11.0  13.0  46.0  41.0   32.0   
9            29.0  1.7  0.37  0.13  1.6  12.0  14.0  45.0  49.0   26.0   
10           29.0  1.7  0.42  0.11  1.7  15.0  17.0  42.0  51.0   40.0   

feature  RAINFALL    RH  SO2  THC  WD_HR  WIND_DIREC  WIND_SPEED  WS_HR  
2             0.0  50.0  3.0  1.7  269.0       260.0         3.0    2.3  
3             0.0  51.0  2.9  1.7  261.0       265.0         3.5    2.9  
4             0.0  51.0  2.4  1.7  269.0       276.0         3.2    3.3  
5             0.0  54.0  2.4  1.6  267.0       267.0         3.3    3.6  
6             0.0  58.0  2.1  1.6  270.0       278.0         3.1    3.0  
7             0.0  63.0  2.6  1.7  278.0       278.0         2.0    2.0  
8             0.0  66.0  2.9  1.7  276.0       278.0         1.9    2.0  
9             0.0  67.0  2.8  1.8  281.0       283.0         1.6    1.8  
10            0.0  65.0  2.9  1.8  243.0       220.0         1.2    0.9

In [60]:
a = np.array([[7.7]])

In [73]:
a.reshape((1,))

array([7.7])

In [75]:
a[0, 0]

7.7

In [20]:
X[147, :]

array([51., 45., 46., 38., 39., 36., 47., 55., 60., 73., 77., 62., 63.,
       70., 79., 93., 87., 96.])

In [98]:
for i in [ 77.,  74.,  69.,  65.,  66.,  75.,  79.,  91.,  92., 116., 112.,97., 107., 112., 127., 133., 122., 122.]:
    print(i in X[100, :])

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [18]:
mdfs[1]

PM2.5   PM10
0     58.0   91.0
1     59.0  104.0
2     57.0   87.0
3     59.0   91.0
4     64.0   83.0
5     64.0   76.0
6     60.0   73.0
7     55.0   66.0
8     54.0   88.0
9     61.0   97.0
10    67.0  101.0
11    72.0   88.0
12    58.0   75.0
13    48.0   62.0
14    36.0   74.0
15    38.0   72.0
16    40.0   79.0
17    42.0   79.0
18    46.0   92.0
19    57.0  120.0
20    76.0  116.0
21    74.0  113.0
22    71.0   84.0
23    50.0   68.0
24    41.0   72.0
25    45.0   71.0
26    48.0   77.0
27    43.0   54.0
28    19.0   43.0
29     9.0   40.0
..     ...    ...
450   80.0  143.0
451   85.0  148.0
452   95.0  151.0
453   99.0  159.0
454  109.0  155.0
455  105.0  153.0
456  104.0  137.0
457   95.0  136.0
458   88.0  133.0
459   81.0  124.0
460   78.0  118.0
461   75.0  107.0
462   72.0  108.0
463   60.0   99.0
464   50.0  105.0
465    0.0    0.0
466   51.0    0.0
467   69.0  133.0
468   85.0  117.0
469   76.0  111.0
470   58.0  101.0
471   43.0   99.0
472   37.0   93.0
473   30.0   93.0
474   39.0   85.0
475   44.0   87.0
476   48.0   79.0
477   43.0   75.0
478   37.0   85.0
479   41.0   97.0

[480 rows x 2 columns]

In [21]:
y

array([[61.],
       [67.],
       [72.],
       ...,
       [51.],
       [48.],
       [49.]])

In [22]:
norm_theta

array([[28.39755839],
       [-4.45330872],
       [ 2.12965279],
       [-3.32096469],
       [ 2.43711245],
       [ 9.89636874],
       [-1.27055567],
       [-0.03792362],
       [-3.23876269],
       [25.09174963],
       [ 2.41332511],
       [-0.51619257],
       [-1.28303912],
       [ 0.88566275],
       [-1.82602789],
       [-0.25125377],
       [-1.35480615],
       [ 3.62710105],
       [ 3.06946685]])

In [ ]:
[[28.39755839],
       [-4.45330872],
       [ 2.12965279],
       [-3.32096469],
       [ 2.43711245],
       [ 9.89636874],
       [-1.27055567],
       [-0.03792362],
       [-3.23876269],
       [25.09174963],
       [ 2.41332511],
       [-0.51619257],
       [-1.28303912],
       [ 0.88566275],
       [-1.82602789],
       [-0.25125377],
       [-1.35480615],
       [ 3.62710105],
       [ 3.06946685]]