In [1]:
import numpy as np

In [2]:
def h(X, theta):
    return np.dot(X, theta)

In [8]:
def gradient_descent(theta, h,  X, y, eta, n_iters):
    m, n = X.shape
    
    for i in range(n_iters):
        grad = (1 / m) * np.sum(h(X, theta) - y)
        
        grad_square_sum = grad**2 + grad_square_sum
        
        theta = theta - eta * grad / np.sqrt(grad_square_sum)
        
    return theta

In [18]:
a = np.arange(4*7).reshape(7, 4)
b = np.arange(7).reshape(7, 1)

In [19]:
b

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [14]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [22]:
(a*b).shape

(7, 4)

In [27]:
b**2

array([[ 0],
       [ 1],
       [ 4],
       [ 9],
       [16],
       [25],
       [36]])

In [29]:
np.sqrt(b) / np.sqrt(b+1)

array([[ 0.        ],
       [ 0.70710678],
       [ 0.81649658],
       [ 0.8660254 ],
       [ 0.89442719],
       [ 0.91287093],
       [ 0.9258201 ]])

In [44]:
a = np.arange(5*7).reshape(7, 5)
b = np.arange(7).reshape(7 , 1)

In [45]:
for i, example in enumerate(zip(a, b)):
    xx, yy = example
    print(i, xx, yy)

0 [0 1 2 3 4] [0]
1 [5 6 7 8 9] [1]
2 [10 11 12 13 14] [2]
3 [15 16 17 18 19] [3]
4 [20 21 22 23 24] [4]
5 [25 26 27 28 29] [5]
6 [30 31 32 33 34] [6]


In [46]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [47]:
np.delete(b, [2,3,6], axis=0)

array([[0],
       [1],
       [4],
       [5]])

In [48]:
b

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6]])