In [1]:
import numpy as np

In [2]:
a = np.arange(3*4).reshape((3,4))

In [16]:
p = np.random.randint(100, size=(3,4))

In [21]:
p = p.astype(np.float32)

In [18]:
q = np.array([
    [63, 93, 49, 64],
    [15, 54, 39, 92],
    [41, 90, 73, 82]
])

In [20]:
q = q.astype(np.float32)

In [30]:
q

array([[ 63.,  93.,  49.,  64.],
       [ 15.,  54.,  39.,  92.],
       [ 41.,  90.,  73.,  82.]], dtype=float32)

In [31]:
p

array([[ 49.,  93.,  63.,  64.],
       [ 39.,  54.,  15.,  92.],
       [ 73.,  90.,  41.,  82.]], dtype=float32)

In [41]:
x = np.array([13, 55, 77]).astype(np.float32).reshape(-1, 1)

In [42]:
y = np.array([77, 55, 13]).astype(np.float32).reshape(-1, 1)

In [43]:
hx = np.dot(np.dot(np.linalg.pinv(np.dot(p.T,p)),p.T),x)

In [53]:
hy = np.dot(np.dot(np.linalg.pinv(np.dot(q.T,q)),q.T),x)

In [54]:
hx

array([[ 1.58880973],
       [-0.09693565],
       [-1.03935349],
       [ 0.15066576]], dtype=float32)

In [55]:
hy

array([[-1.03935373],
       [-0.09693562],
       [ 1.58881021],
       [ 0.15066591]], dtype=float32)

In [51]:
p

array([[ 49.,  93.,  63.,  64.],
       [ 39.,  54.,  15.,  92.],
       [ 73.,  90.,  41.,  82.]], dtype=float32)

In [48]:
x

array([[ 13.],
       [ 55.],
       [ 77.]], dtype=float32)

In [52]:
q

array([[ 63.,  93.,  49.,  64.],
       [ 15.,  54.,  39.,  92.],
       [ 41.,  90.,  73.,  82.]], dtype=float32)

In [50]:
y

array([[ 77.],
       [ 55.],
       [ 13.]], dtype=float32)